FROM docker.io/library/ubuntu:22.04

ARG HOST=${HOST}

ARG PATH_PROJECT=/eip-x
ARG PATH_MAIN=${PATH_PROJECT}/axiom-eth

ENV HOME /root
WORKDIR ${PATH_MAIN}

# version required according to rust-toolchain of axiom-eth repo
ARG RUST_NIGHTLY="2022-10-28"
ARG BRANCH_NAME=eip-x
ARG REPO_URL="https://github.com/clawbird/axiom-eth.git"

ENV RUSTUP_HOME=$HOME/.rustup \
  CARGO_HOME=$HOME/.cargo \
  PATH=$HOME/cargo/bin:$PATH \
  HOST=${HOST}

COPY ./.env.example ${PATH_PROJECT}/.env.example
COPY ./.env ${PATH_PROJECT}/.env

RUN set -e && \
  apt-get -y update --fix-missing && \
  apt-get -y upgrade && \
  apt-get install -y build-essential pkg-config && \
  # # Helios-specific requirement
  # apt-get install -y libfontconfig-dev && \
  apt-get install -y git curl wget jq lsof unzip vim && \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain nightly -y && \
  rustup component add rust-src rustfmt clippy && \
  rustup target add wasm32-unknown-unknown && \
  rustup toolchain install "nightly-${RUST_NIGHTLY}" --profile minimal --component rustfmt && \
  rustup default "nightly-${RUST_NIGHTLY}" && \
  rustup override set "nightly-${RUST_NIGHTLY}" && \
  # install wasm target into nightly toolchain
  rustup target add wasm32-unknown-unknown --toolchain "nightly-${RUST_NIGHTLY}" && \
  . $HOME/.cargo/env && \
  rustc --version && \
  rustup show && \
  cd ${PATH_PROJECT} && \
  git clone ${REPO_URL} && \
  cd axiom-eth && \
  git fetch origin ${BRANCH_NAME}:${BRANCH_NAME} && \
  git checkout ${BRANCH_NAME} && \
  cp ${PATH_PROJECT}/.env.example ${PATH_PROJECT}/axiom-eth/axiom-eth/.env.example && \
  cp ${PATH_PROJECT}/.env ${PATH_PROJECT}/axiom-eth/axiom-eth/.env && \
  . ${PATH_PROJECT}/axiom-eth/axiom-eth/.env && \
  # if you get this error
  # error: package `xxx vx.y.z` cannot be built because it requires rustc 1.70.0 or newer,
  # while the currently active rustc version is 1.66.0-nightly
  # Either upgrade to rustc 1.70.0 or newer, or use
  # cargo update -p xxx@x.y.z --precise ver
  # where `ver` is the latest version of `xxx` supporting rustc 1.66.0-nightly
  #
  # for example, if xxx is anstyle-parse, then go to
  # https://crates.io/crates/anstyle-parse/versions
  # and replace `ver` with a version v1.64.0 instead of the latest that uses v1.70.0
  # and update or add it to the below
  cargo update -p anstyle@1.0.4 --precise 1.0.2 && \
  cargo update -p anstyle-parse@0.2.2 --precise 0.2.1 && \
  cargo update -p clap@4.4.6 --precise 4.3.24 && \
  cargo update -p clap_lex@0.5.1 --precise 0.5.0 && \
  cargo build --verbose && \
  cargo run --bin header_chain --release -- --help

EXPOSE 7878

CMD tail -f /dev/null
